### PR TITLE
WIP DO NOT REVIEW:  V1.0 backports 18 07 04

### PR DESCRIPTION
**Pull request by manalibhutiyani**
PR: #4265 -- test: add k8s 1.12 test framework (@aanm) 
PR: #4634 -- test: update k8s to 1.8.14, 1.10.4 and 1.11.0 (@aanm) 
PR: #4635 -- update cilium to golang 1.10.3 (@aanm)
PR: #4636 -- Fix PolicyRevision of endpoint bumped prematurely (@aanm)
PR: #4653 -- tests: Update cilium-builder in unit tests to 2018-06-21 (@aanm)
PR: #4655 -- test: Use latest stable etcd and consul images (@aanm)
PR: #4663 -- backport: Only check merged PRs (@raybejjani) 
PR: #4682 -- pkg/policy: take into account To / FromRequires when computing L4 policy (@ianvernon)

@aanm I have skipped `3fa23d0704af63bf9b4de17b8b30e818b3cd8fef ` ("ginkgo-kubernetes-all.Jenkinsfile: move k8s 1.10 and 1.12 to same stage")
since this was reverted in master recently. Please let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4737)

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Double checked `test: set default CRI socket` https://github.com/cilium/cilium/pull/4737/commits/a31ac9cc763e764b77b24ec7f21ea3e821bc8d38 was backported correctly to 1.0 with Andre.

**Comment by manalibhutiyani** [comment]
Looks like envoy build is failing:
```
18:16:47     k8s1-1.11: [1,837 / 1,853] Compiling external/envoy/source/common/upstream/upstream_impl.cc; 13s local ... (2 actions running)
18:16:47     k8s1-1.11: 
18:17:14     k8s1-1.11: ERROR: /root/.cache/bazel/_bazel_root/e3bb2978717df7858b43846d8c1242eb/external/envoy/source/server/config_validation/BUILD:74:1: undeclared inclusion(s) in rule '@envoy//source/server/config_validation:server_lib':
18:17:14     k8s1-1.11: this rule is missing dependency declarations for the following files included by 'external/envoy/source/server/config_validation/server.cc':
18:17:14     k8s1-1.11:   'bazel-out/k8-opt/bin/external/envoy/source/server/config_validation/_virtual_includes/dispatcher_lib/server/config_validation/dns.h'
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: Target //:envoy failed to build
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: Use --verbose_failures to see the command lines of failed build steps.
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: INFO: Elapsed time: 1260.752s, Critical Path: 42.85s
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: INFO: 1427 processes, local.
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: FAILED: Build did NOT complete successfully
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: FAILED: Build did NOT complete successfully
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: Makefile:61: recipe for target 'envoy-release' failed
18:17:14     k8s1-1.11: make[1]: Leaving directory '/go/src/github.com/cilium/cilium/envoy'
18:17:14     k8s1-1.11: make[1]: *** [envoy-release] Error 1
18:17:14     k8s1-1.11: 
18:17:14     k8s1-1.11: make: *** [envoy] Error 2
18:17:14     k8s1-1.11: Makefile:25: recipe for target 'envoy' failed
18:17:14     k8s1-1.11: The command '/bin/sh -c make LOCKDEBUG=$LOCKDEBUG PKG_BUILD=1 DESTDIR=/tmp/install clean-container build install' returned a non-zero code: 2
18:17:14     k8s1-1.11: Makefile:124: recipe for target 'docker-image' failed
18:17:14     k8s1-1.11: make: *** [docker-image] Error 2
```

**Comment by manalibhutiyani** [comment]
Using the same technique as @raybejjani from https://github.com/cilium/cilium/pull/4641
https://github.com/cilium/cilium/commit/8e009683517727f58ace61aae5f80d76f3bb1c54

Please see https://github.com/cilium/cilium/pull/4641 for more reference about the envoy SHA fix. I have used the same method here.

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
The envoy SHA changes did not work on 1.0. @aanm @jrajahalme @raybejjani @rlenglet Please advise if there is any other way?

**Comment by manalibhutiyani** [comment]
getting following errors with changes to envoy SHA

```
19:19:23     
19:19:41     k8s1-1.7: ERROR: /go/src/github.com/cilium/cilium/envoy/BUILD:149:1: C++ compilation of rule '//:cilium_network_filter_lib' failed (Exit 1)
19:19:41     k8s1-1.7: 
19:19:41     k8s1-1.7: cilium_network_filter.cc:22:18: error: 'NetworkFilterFactoryCb' in namespace 'Envoy::Server::Configuration' does not name a type
19:19:41     k8s1-1.7:    Configuration::NetworkFilterFactoryCb
19:19:41     k8s1-1.7:                   ^~~~~~~~~~~~~~~~~~~~~~
19:19:41     k8s1-1.7: cilium_network_filter.cc:29:18: error: 'NetworkFilterFactoryCb' in namespace 'Envoy::Server::Configuration' does not name a type
19:19:41     k8s1-1.7:    Configuration::NetworkFilterFactoryCb
19:19:41     k8s1-1.7:                   ^~~~~~~~~~~~~~~~~~~~~~
19:19:41     k8s1-1.7: In file included from cilium_network_filter.cc:6:0:
19:19:41     k8s1-1.7: bazel-out/k8-opt/bin/external/envoy/include/envoy/registry/_virtual_includes/registry/envoy/registry/registry.h: In instantiation of 'class Envoy::Registry::RegisterFactory<Envoy::Server::Configuration::CiliumNetworkConfigFactory, Envoy::Server::Configuration::NamedNetworkFilterConfigFactory>':
19:19:41     k8s1-1.7: cilium_network_filter.cc:46:5:   required from here
19:19:41     k8s1-1.7: bazel-out/k8-
19:19:41     k8s1-1.7: 
19:19:41     k8s1-1.7: FAILED: Build did NOT complete successfully
19:19:41     k8s1-1.7: 
19:19:41     k8s1-1.7: FAILED: Build did NOT complete successfully
19:19:41     k8s1-1.7: 
19:19:41     k8s1-1.7: make[1]: *** [envoy-release] Error 1
19:19:41     k8s1-1.7: Makefile:61: recipe for target 'envoy-release' failed
19:19:41     k8s1-1.7: make[1]: Leaving directory '/go/src/github.com/cilium/cilium/envoy'
19:19:41     k8s1-1.7: make: *** [envoy] Error 2
19:19:41     k8s1-1.7: Makefile:25: recipe for target 'envoy' failed
19:19:42     k8s1-1.7: The command '/bin/sh -c make LOCKDEBUG=$LOCKDEBUG PKG_BUILD=1 DESTDIR=/tmp/install clean-container build install' returned a non-zero code: 2
19:19:42     k8s1-1.7: Makefile:124: recipe for target 'docker-image' failed
19:19:42     k8s1-1.7: make: *** [docker-image] Error 2
```

**Comment by rlenglet** [comment]
If a PR has both a change of ENVOY_SHA and changes to Cilium’s Envoy filters, you can’t just pick the ENVOY_SHA change. The filters code is strongly tied to the ENVOY_SHA.
What goes wrong when you apply the complete PR unchanged?

**Comment by manalibhutiyani** [comment]
@rlenglet 8e00968 also back ported only the ENVOY SHA and not all the changes, and hence I tried the exact same thing to solve the issue. I did ask in the development channel if this was a safe thing to do.

A question for you and @jrajahalme Is the whole PR https://github.com/cilium/cilium/commit/6477c13882a6f36684a68fc4ef2af0861054a130 ok to be back ported to 1.0? It was not marked as ok to be back ported. Please let me know

**Comment by manalibhutiyani** [comment]
@rlenglet Was https://github.com/cilium/cilium/commit/8e009683517727f58ace61aae5f80d76f3bb1c54 a correct backport to v1.1? None of the filter changes were back ported in that case as well?

**Comment by tgraf** [comment]
1b882e4 was reverted as well

**Comment by manalibhutiyani** [comment]
I am skipping PR: #4635 -- update cilium to golang 1.10.3 (@aanm) as per discussion on slack to avoid going in the envoy compilation rabbit hole!

**Comment by manalibhutiyani** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/4752 minus the 1.10 golang changes
