### PR TITLE
bpf: Fix defines in policy.h

### PR DESCRIPTION
**Pull request by pchaigno**
Commit 501332b ("bpf: Remove DROP_ALL define") forgot to remove an `#else` statement, resulting in a compilation error if `policy.h` is  included twice.

Marking for backports as I hit this while working on a v1.8 backport.

IMO, we should really enforce the use of #ifdef comments and indentations to avoid this sort of bugs.

Fixes: https://github.com/cilium/cilium/pull/5379

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good, and agreed for the need on comments/indent for the various preprocessor conditions.

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by pchaigno** [comment]
The previously failing test is passing. Marking as ready to merge.
