### PR TITLE
Fix potential deadlock in pod identity updates

### LINKED ISSUE #16236: Unable to update ipcache map entry on pod add causing DNS resolving failure in the pods.
## Bug report

**General Information**

- Cilium version: 1.10.0.rc1
- Kernel version: `Linux ip-172-18-46-124 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Using EKS, with `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Generate and upload a system zip:
Too large to upload to github so created a google drive share. 

https://drive.google.com/file/d/1vL8W7cg6-CSmCmFZtWk3PDLc6og4skfQ/view?usp=sharing

**How to reproduce the issue**

Hey Guys, I am running cilium 1.10.0.rc1 with eks 1.18 with aws eni mode (withous chaining mode)

I am having this weird issue that both of the two pods below cannot resolve any dns / talk to coredns in the cluster. It keeps getting timeout somehow. This is the log in the cilium pod
```
level=warning msg="Unable to update ipcache map entry on pod add" error="ipcache entry for podIP 172.18.46.215: unable to overwrite source \"custom-resource\" with source \"k8s\"" hostIP=172.18.46.215 k8sNamespace=pelican k8sPodName=pelican-bf8c54f86-4zfgp podIP=172.18.46.215 podIPs="[{172.18.46.215}]" subsys=k8s-watcher
level=warning msg="Unable to update ipcache map entry on pod add" error="ipcache entry for podIP 172.18.59.200: unable to overwrite source \"custom-resource\" with source \"k8s\"" hostIP=172.18.59.200 k8sNamespace=sentry k8sPodName=sentry-sentry-redis-slave-0 podIP=172.18.59.200 podIPs="[{172.18.59.200}]" subsys=k8s-watcher
```

From what I can see that this cilium pod somehow has issue that the garbage collector hasn't been running for a day. When I checked the log above it's already 05/19 UTC time

```
2021-05-18T14:54:15.211318802Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:55:15.211917883Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:56:15.213160212Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:57:15.214740217Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:58:01.388798338Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777255 subsys=policy
2021-05-18T14:58:01.388819817Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2021-05-18T14:58:01.393484089Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777228 subsys=policy
2021-05-18T14:58:02.389790661Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2021-05-18T14:58:15.216149319Z level=info msg="FQDN garbage collector work deleted 7 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,qlb.syd1.fln-dev.net.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:59:15.216945537Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:00:15.218293017Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:01:15.219695212Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:02:15.221210254Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
```

Cilium itself seems to be healthy on this node
```
$ kubectl exec -it cilium-lx849 -n kube-system -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, wait-for-node-init (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.18+ (v1.18.9-eks-d1db3c) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens5 172.18.46.124 (Direct Routing)]
Cilium:                 Ok   1.10.0-rc1 (v1.10.0-rc1-efc15cd)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 24/32 allocated,
BandwidthManager:       EDT with BPF   [ens5]
Host Routing:           Legacy
Masquerading:           Disabled
Controller Status:      109/109 healthy
Proxy Status:           OK, ip 172.18.46.202, 16 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 215.86   Metrics: Ok
Encryption:             Disabled
Cluster health:         10/10 reachable   (2021-05-19T04:14:37Z)

```

But I can see every time I do a dns lookup the cilium pod fails talking to coredns
172.18.55.216 is the coredns pod ip
```
$ kubectl exec -it cilium-lx849 -n kube-system -- cilium monitor | grep 172.18.46.215
Policy verdict log: flow 0xe5effeec local EP ID 1574, remote ID 38547, proto 17, egress, action redirect, match L3-L4, 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
```
If I delete this cilium pod on this node, a new one spun up by the daemonset and everything seems to be working again, but this issue happens occasionally every couple of hours

### LINKED ISSUE #16300: Memory leak with FQDN policies
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
Daemon: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd6
```
- Kernel version (run `uname -a`)
```
Linux 5.8.0-40-lowlatency #45~20.04.1-Ubuntu SMP PREEMPT Fri Jan 15 12:34:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
v1.20.4+k3s1
```

- Generate and upload a system zip:
[cilium-sysdump-20210525-150354.zip](https://github.com/cilium/cilium/files/6539133/cilium-sysdump-20210525-150354.zip)

**Description**

One pod has memory leak. It happened a few days ago with another node(pod), restart pod had help
image

### PR DESCRIPTION
**Pull request by jrajahalme**
Make IdentitySelectionUpdated() callbacks lock-free by queueing them
while still holding selectorcache lock (to keep FIFO order) and
calling from a goroutine not holding any locks. This prevents
deadlocks caused by the implementation of IdentitySelectionUpdated()
taking locks such as endpoint or selectorcache locks.

```release-note
Potential deadlock in pod identity updates has been fixed.
```

Fixes: #16236
Fixes: #16300

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
the unit tests have failed:
```
 	 # github.com/cilium/cilium/pkg/fqdn/dnsproxy [github.com/cilium/cilium/pkg/fqdn/dnsproxy.test]
	 pkg/fqdn/dnsproxy/proxy_test.go:184:36: not enough arguments in call to testSelectorCache.UpdateIdentities
	 	have ("github.com/cilium/cilium/pkg/identity/cache".IdentityCache, nil)
	 	want ("github.com/cilium/cilium/pkg/identity/cache".IdentityCache, "github.com/cilium/cilium/pkg/identity/cache".IdentityCache, *sync.WaitGroup)
	 make: *** [tests-privileged] Error 1
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
> the unit tests have failed:
> 
> ```
>  	 # github.com/cilium/cilium/pkg/fqdn/dnsproxy [github.com/cilium/cilium/pkg/fqdn/dnsproxy.test]
> 	 pkg/fqdn/dnsproxy/proxy_test.go:184:36: not enough arguments in call to testSelectorCache.UpdateIdentities
> 	 	have ("github.com/cilium/cilium/pkg/identity/cache".IdentityCache, nil)
> 	 	want ("github.com/cilium/cilium/pkg/identity/cache".IdentityCache, "github.com/cilium/cilium/pkg/identity/cache".IdentityCache, *sync.WaitGroup)
> 	 make: *** [tests-privileged] Error 1
> ```

Fixed, thanks!

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Test flake #14598 hit in test-1.21-4.9, seems unrelated (deathstar.default.svc.cluster.local not resolved by kube-dns even though the service exists and has 3 backends).

**Comment by jrajahalme** [comment]
rebasing to pick up CI fixes.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
unrelated CI fail on test-1.21-4.9 tracked in slack: https://isovalent.slack.com/archives/C0139GWK3QU/p1626094042225600

**Comment by jrajahalme** [comment]
test-1.21-4.9

**Comment by jrajahalme** [comment]
ConformanceEKS test flake caused by #16867, fixed in https://github.com/cilium/cilium-cli/pull/422

**Review by aanm — APPROVED** [review]
