### PR TITLE
Resiliency: Add retry logic to attempt to clear out stale hostip

### PR DESCRIPTION
**Pull request by derailed**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Resiliency: Add retry logic to attempt to clear out stale hostip

NOTE: Depends on PR: https://github.com/cilium/cilium/pull/27614

When the daemon initializes it attempts to clean out stale host ips. 
This process only occurs one time irregardless of errors occurring during that reconciliation.

- Add retry logic on the daemon to attempt to clear out stale host ips should errors occurred during that process.
    
> NOTE: Not super sure on the best way to handle this use case??
This will potentially put the brakes on while constructing the daemon.
This ctor code is currently very procedural (not to mention a mile long!) 
as each step depends on the resolution of the previous one?
    
Fixes: #issue-number

Signed-off-by: Fernand Galiana <fernand.galiana@gmail.com>

### CODE REVIEW

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -19,6 +19,7 @@ import (
 	"github.com/sirupsen/logrus"
 	"github.com/vishvananda/netlink"
 	"golang.org/x/sync/semaphore"
+	"k8s.io/apimachinery/pkg/util/wait"
```
Comment (bimmlerd) [inline daemon/cmd/daemon.go]: I think we have `pkg/backoff` in cilium for exponential backoffs, did you consider using that instead of k8s?

File: daemon/cmd/daemon.go [hunk 2]
```diff
@@ -1065,13 +1059,30 @@ func newDaemon(ctx context.Context, cleaner *daemonCleanup, params *daemonParams
...
-		d.restoreCiliumHostIPs(false, router4FromK8s)
-	}
+	ipv6, router := false, router4FromK8s
 	if option.Config.EnableIPv6 {
-		d.restoreCiliumHostIPs(true, router6FromK8s)
+		ipv6, router = true, router6FromK8s
 	}
 
+	bo := wait.Backoff{
+		Duration: 500 * time.Millisecond,
```
Comment (bimmlerd) [inline daemon/cmd/daemon.go]: I think that's a long time to wait before retrying given this is on the critical path for daemon startup, I'd shorten this.

**Review by bimmlerd — CHANGES_REQUESTED** [review]
Given we've just logged a warning before, I think we should delay startup by as much. generally lgtm, though I have no idea whether these errors should be considered retryable

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: @bimmlerd  Thanks for your input David! Best I can tell `pkg/backoff` expects you to manage the retry loop, thus opted for using k8s retry built-in instead which felt more appropriate for this use case.

File: daemon/cmd/daemon.go (hunk 2 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: Good point! I am not versed with netlink hence not sure what would be a reasonable delay to retry the service? Lowering it down to 100ms. Please pipe in if you think otherwise. Thank you!

**Comment by bimmlerd** [comment]
Yeah I don't know enough about netlink either, I'll defer my review to @ti-mo.

File: daemon/cmd/daemon.go [hunk 3]
```diff
@@ -1065,13 +1059,30 @@ func newDaemon(ctx context.Context, cleaner *daemonCleanup, params *daemonParams
 	// router IPs from the K8s resources if we weren't able to restore them
 	// from the fs. We must do this after IPAM because we must wait until the
 	// K8s resources have been synced. Part 2/2 of restoration.
-	if option.Config.EnableIPv4 {
-		d.restoreCiliumHostIPs(false, router4FromK8s)
-	}
+	ipv6, router := false, router4FromK8s
 	if option.Config.EnableIPv6 {
-		d.restoreCiliumHostIPs(true, router6FromK8s)
```
Comment (jibi) [inline daemon/cmd/daemon.go:1075]: I think this drifts from the original original behavior: in case both ipv4 and ipv6 are enabled, only v6 addresses will be restored, while before both v4 and v6 would have been restored

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (jibi) [reply daemon/cmd/daemon.go]: I would have also suggested to use `pkg/backoff`, mostly for consistency with the rest of the codebase, although I do agree that `wait` seems more handy to deal with retries :+1:

**Review by jibi — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 3 above)
Comment (derailed) [reply daemon/cmd/daemon.go:1075]: Rats! Great catch. Thank you Gilberto!

File: daemon/cmd/daemon.go [hunk 4]
```diff
@@ -343,25 +345,21 @@ func (d *Daemon) restoreCiliumHostIPs(ipv6 bool, fromK8s net.IP) {
...
 func removeOldRouterState(ipv6 bool, restoredIP net.IP) error {
 	l, err := netlink.LinkByName(defaults.HostDevice)
-	if errors.As(err, &netlink.LinkNotFoundError{}) && restoredIP == nil {
-		// There's no old state remove as the host device doesn't exist and
-		// there's no restored IP anyway.
-		return nil
-	} else if err != nil {
-		return err
+	if err != nil {
+		if errors.As(err, &netlink.LinkNotFoundError{}) && restoredIP == nil {
```
Comment (ti-mo) [inline daemon/cmd/daemon.go]: Nit: `if errors.As() ... { return nil }` can be lifted out of the `if err != nil {}` block, it already does its own nil checking. If the `As` doesn't match, execution will fall through to the regular `if err != nil {}`, where the retry is issued.

Less indentation reads a bit easier.

File: daemon/cmd/daemon.go [hunk 5]
```diff
@@ -343,25 +345,21 @@ func (d *Daemon) restoreCiliumHostIPs(ipv6 bool, fromK8s net.IP) {
...
+			// There's no old state remove as the host device doesn't exist and
+			// there's no restored IP anyway.
+			return nil
+		}
+		return resiliency.NewRetryableErr(err)
```
Comment (ti-mo) [inline daemon/cmd/daemon.go]: Could this be named `resiliency.Retry()` instead? It makes sense to use the imperative 'retry' here, since we want to signal an underlying layer to retry the operation. It also saves some typing and reading. :) I'd name the wrapper type `type Retryable` for brevity as well. Perhaps at some point it will hold more than just an error.

File: daemon/cmd/daemon.go [hunk 6]
```diff
@@ -1065,13 +1059,29 @@ func newDaemon(ctx context.Context, cleaner *daemonCleanup, params *daemonParams
...
-	}
-	if option.Config.EnableIPv6 {
-		d.restoreCiliumHostIPs(true, router6FromK8s)
+	bo := wait.Backoff{
+		Duration: 100 * time.Millisecond,
+		Factor:   1,
+		Jitter:   0.1,
+		Steps:    3,
+	}
+	err = wait.ExponentialBackoffWithContext(ctx, bo, func(ctx context.Context) (done bool, err error) {
```
Comment (ti-mo) [inline daemon/cmd/daemon.go]: Will this retry forever? At which point do we give up and crash the agent? (or drop the operation?)

File: daemon/cmd/daemon.go (hunk 5 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: Good point Timo! I am open to a rename but I think for the time being the naming make sense. 
`Retry()` feels a bit more obscure since we are not performing an actual retry here but wrapping the error to potentially trap it further up the chain. 
In the future, should we opt that additional context around the condition would be deemed useful we could rename accordingly?

File: daemon/cmd/daemon.go (hunk 6 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: This will retry at most 3 times before we give up.

File: daemon/cmd/daemon.go (hunk 4 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: Indeed. Great catch!

File: daemon/cmd/daemon.go [hunk 7]
```diff
@@ -343,12 +345,7 @@ func (d *Daemon) restoreCiliumHostIPs(ipv6 bool, fromK8s net.IP) {
 	}
 
 	restoredIP := node.RestoreHostIPs(ipv6, fromK8s, fromFS, cidrs)
-	if err := removeOldRouterState(ipv6, restoredIP); err != nil {
-		log.WithError(err).Warnf(
-			"Failed to remove old router IPs (restored IP: %s) from cilium_host. Manual intervention is required to remove all other old IPs.",
-			restoredIP,
```
Comment (christarazi) [inline daemon/cmd/daemon.go:349]: I think it can still be nice to know what the restored IP is in the log msg so that the user can know which old IPs to remove

File: daemon/cmd/daemon.go [hunk 8]
```diff
@@ -1065,13 +1059,29 @@ func newDaemon(ctx context.Context, cleaner *daemonCleanup, params *daemonParams
...
+			errs = errors.Join(errs, d.restoreCiliumHostIPs(true, router6FromK8s))
+		}
+		if resiliency.IsRetryable(errs) {
+			log.WithError(errs).Warnf("Failed to remove old router IPs from cilium_host. Retrying...")
+			return false, nil
+		}
+		return true, errs
+	})
+	if err != nil {
+		log.WithError(err).Error("Restore host ips failed. Manual intervention is required to remove all other old IPs.")
```
Comment (christarazi) [inline daemon/cmd/daemon.go]:
```suggestion
		log.WithError(err).Error("Restore of the cilium_host IP failed. Manual intervention is required to remove all other old IPs.")
```

Just to not differ too much from the original log msg.

File: daemon/cmd/daemon.go (hunk 6 above)
Comment (christarazi) [inline daemon/cmd/daemon.go]: I feel like this boilerplate should ideally be collapsed down into a helper function, so that the daemon code doesn't just increasingly become longer each time we add resiliency to the restore paths.

**Review by christarazi — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 7 above)
Comment (derailed) [reply daemon/cmd/daemon.go:349]: No loss here, as we moved the log message further up the stack. 
Hence failed deletions will still log the respective host IPs that could not be deleted.

File: daemon/cmd/daemon.go (hunk 8 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: Good catch! Tx Chris!!

File: daemon/cmd/daemon.go (hunk 6 above)
Comment (derailed) [reply daemon/cmd/daemon.go]: Indeed! I'll float an idea here and we can backfill the other prs if the proposal is deemed acceptable...

**Review by christarazi — APPROVED** [review]
Very clean now with the helper!

**Review by bimmlerd — APPROVED** [review]

File: daemon/cmd/daemon.go (hunk 5 above)
Comment (ti-mo) [reply daemon/cmd/daemon.go]: Sure, then what about popping the `New` and/or `Err` parts off of the function name? We'd end up with `err = errors.Join(err, resiliency.Retryable(fmt.Errorf("failed to remove IP %s: %w", a.IP, e)))`. That pairs up nicely with `if resiliency.IsRetryable(errs) { ... }`. (Retryable() in the callee caught by IsRetryable in the caller)

And since we're exposing `IsRetryable()` as the canonical way of checking retryable errors, we should also unexport `type RetryableErr`.

> In the future, should we opt that additional context around the condition would be deemed useful we could rename accordingly?

By that time, there will be so many users that this turns into a huge change, meaning increased pain during backports. Let's just get this right from the beginning. :slightly_smiling_face:

Comment (derailed) [reply daemon/cmd/daemon.go]: Ok I'll make it so. Tx Timo!

**Comment by christarazi** [comment]
It looks like the "build commits" job is failing because one of the commits is failing to build:

```
# github.com/cilium/cilium/daemon/cmd
Error: cmd/ciliumendpoints.go:103:22: undefined: resiliency.NewRetryableErr
Error: cmd/ciliumendpoints.go:130:21: undefined: resiliency.NewRetryableErr
```

Basically, each commit should be able to build independently.

File: daemon/cmd/daemon.go [hunk 9]
```diff
@@ -343,12 +344,7 @@ func (d *Daemon) restoreCiliumHostIPs(ipv6 bool, fromK8s net.IP) {
 	}
 
 	restoredIP := node.RestoreHostIPs(ipv6, fromK8s, fromFS, cidrs)
-	if err := removeOldRouterState(ipv6, restoredIP); err != nil {
-		log.WithError(err).Warnf(
-			"Failed to remove old router IPs (restored IP: %s) from cilium_host. Manual intervention is required to remove all other old IPs.",
-			restoredIP,
-		)
-	}
+	return removeOldRouterState(ipv6, restoredIP)
```
Comment (jibi) [inline daemon/cmd/daemon.go:347]: nit: since all errors returned by `removeOldRouterState` are retryable, can we just decorate the eventual returned error here to make this more explicit (and avoid all the changes to the function)?

**Review by jibi — APPROVED** [review]

**Comment by lmb** [comment]
Please resolve all conversations to get this mergeable.

File: daemon/cmd/daemon.go (hunk 9 above)
Comment (derailed) [reply daemon/cmd/daemon.go:347]: @jibi - not keen on this idea as it should be a `explicit` developer choice here vs assuming all errors return by this call will be deemed retryable. If we were to return a non retryable error later on, devs might not be aware that error will be retried.
