### ISSUE TITLE
CI: Smoke test / conformance-test: 

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14950]
The `Smoke test / conformance-test` is broken on master: https://github.com/cilium/cilium/actions?query=workflow%3A%22Smoke+test%22. E.g., https://github.com/cilium/cilium/runs/1883726775?check_suite_focus=true#step:9:245.

It fails with the following error in `Check prometheus metrics`:
```
# github.com/prometheus/prometheus/cmd/promtool
go/src/github.com/prometheus/prometheus/cmd/promtool/main.go:645:35: not enough arguments in call to api.LabelValues
	have (context.Context, string, time.Time, time.Time)
	want (context.Context, string, []string, time.Time, time.Time)
Error: Process completed with exit code 2.
```

**Comment by pchaigno** [comment]
It started breaking with commit https://github.com/cilium/cilium/commit/ae96b92c30350a78deb11c50ee0b3bbaf5e5e62d, which only touches documentation. So the issue is more likely a dependency that changed.

The `Check prometheus metrics` step has:
```yaml
      - name: Check prometheus metrics
        if: ${{ success() }}
        run: |
          cd $HOME
          cilium_pod=$(kubectl -n kube-system get po -o name --field-selector=status.phase==Running -l 'k8s-app=cilium' -o jsonpath='{.items[0].metadata.name}' )
          kubectl -n kube-system exec $cilium_pod -- sh -c "apt update && apt install curl -y"
          kubectl -n kube-system exec $cilium_pod -- curl http://localhost:9090/metrics > metrics.prom
          go get -u github.com/prometheus/prometheus/cmd/promtool
          cat metrics.prom | $HOME/go/bin/promtool check metrics
```
Presumably we should use a fixed version instead of `go get -u github.com/prometheus/prometheus/cmd/promtool`.

**Comment by jibi** [comment]
I'm not sure I understand the reason of the failure :thinking: 

The signature of the `api.LabelValues()` method in the `client_golang` package changed a couple of months ago: https://github.com/prometheus/client_golang/commit/75d7516f2a100997f739a5bc520bf08bb44a2600.

At the same time, `client_golang` is pinned to `v1.9.0` both in [Cilium](https://github.com/cilium/cilium/blob/master/go.mod#L67) and in [Prometheus](https://github.com/prometheus/prometheus/blob/master/go.mod#L48) (where `promtool` belongs to), and `v1.9.0` still has the old `api.LabelValues()` method signature: https://github.com/prometheus/client_golang/blob/d89cf5af8849fcb6d69f2c16bdf3b910e03d341e/api/prometheus/v1/api.go#L234

so why is `go get` pulling the latest revision of `client_golang`?

**Comment by pchaigno** [comment]
> so why is `go get` pulling the latest revision of `client_golang`?

Are we actually running from the Cilium src dir? https://github.com/cilium/cilium/blob/3b0f6e8666dec1d22c230964ace62417c7b062d1/.github/workflows/smoke-test.yaml#L133

**Comment by jibi** [comment]
Right, but even if we are running from `$HOME`, `client_golang` is pinned to `v1.9.0` in the Prometheus package
