### ISSUE TITLE
CI: oss-fuzz cannot run fuzzer in pkg/fqdn/namemanager

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#41289]
## CI failure

This fuzzer fails the build on oss-fuzz, as seen in https://github.com/cilium/cilium/pull/41288:

https://github.com/cilium/cilium/actions/runs/17088273197/job/48456794251?pr=41288#step:4:846

```
Running go-fuzz -tags gofuzz -func Fuzz -o fuzz.a github.com/cilium/cilium/test/fuzzing
# github.com/cilium/cilium/pkg/fqdn/namemanager
pkg/fqdn/namemanager/fuzz_test.go_fuzz.go:18:28: cannot use t (variable of type *"github.com/AdamKorcz/go-118-fuzz-build/testing".T) as "testing".TB value in argument to hivetest.Logger: *"github.com/AdamKorcz/go-118-fuzz-build/testing".T does not implement "testing".TB (missing method Chdir)
```

It's OK if you run the fuzzer locally via `go test ./pkg/fqdn/namemanager/ -fuzz=FuzzMapSelectorsToNamesLocked -fuzztime=5s`.

Evidently something about oss-fuzz is substituting a different `testing.T` implementation that does not implement the interfaces we need. https://github.com/AdamKorcz/go-118-fuzz-build/pull/24 might move things in the right direction, but the PR is quite old without response, and presumably the fix not only needs to be accepted by upstream but also propagated into whichever oss-fuzz systems rely on it.

Given that the fuzzer is already skipped today, I will just leave it in the skipped category for now.

**Comment by AdamKorcz** [comment]
https://github.com/google/oss-fuzz/pull/13835 should fix this.

**Comment by joestringer** [comment]
@AdamKorcz glad to hear that! Thanks for the update.

**Comment by joestringer** [comment]
I found another workaround in the intermediate period: Using `slog.New(slog.DiscardHandler)` as the logger rather than `hivetest.Logger(f)`.
