### PR TITLE
clustermesh: unbreak test

### PR DESCRIPTION
**Pull request by julianwiedmann**
Error: pkg/clustermesh/remote_cluster_test.go:155:54: too many arguments in call to newGlobalServiceCache
	have (string, string)
	want ("github.com/cilium/cilium/pkg/metrics/metric".Gauge)

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Looks like this was introduced by https://github.com/cilium/cilium/pull/26157.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by giorio94 — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Superseded by https://github.com/cilium/cilium/pull/26294, thanks @giorio94  !
