### ISSUE TITLE
Failed to build in Ubuntu 18.04

### ISSUE THREAD

**Issue by k82cn** [cilium/cilium#13396]
## Bug report

**General Information**

- Cilium version (run `cilium version`): master branch
- Kernel version (run `uname -a`): `Linux VM-0-13-ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): localhost
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

```
ubuntu@VM-0-13-ubuntu:~/go/src/github.com/cilium/cilium$ make
contrib/scripts/check-logging-subsys-field.sh
contrib/scripts/check-fmt.sh
contrib/scripts/check-log-newlines.sh
contrib/scripts/check-missing-tags-in-tests.sh
contrib/scripts/check-assert-deep-equals.sh
contrib/scripts/lock-check.sh
contrib/scripts/rand-check.sh
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/proxylib'
CGO_ENABLED=1 go build  -mod=vendor -ldflags ' -X "github.com/cilium/cilium/pkg/version.ciliumVersion=1.8.90 28d988979 2020-10-02T17:43:25+03:00" -s -w -X "github.com/cilium/cilium/pkg/envoy.RequiredEnvoyVersionSHA=1177896bebde79915fe5f9092409bf0254084b4e" -X "github.com/cilium/cilium/pkg/datapath/loader.DatapathSHA=4a6b5fddfde9daf83da24ed5def0fd4b74711b6d" -extldflags -Wl,-soname,libcilium.so.1' -tags=osusergo  -o libcilium.so.1 -buildmode=c-shared
ln -sf libcilium.so.1 libcilium.so || cp libcilium.so.1 libcilium.so
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/proxylib'
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/envoy'
  SKIP  envoy/
cilium-envoy has been moved to github.com/cilium/proxy
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/envoy'
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf'
set -e; \
if [ "" != "" ]; then \
         :  " [-DALLOW_ICMP_FRAG_NEEDED]"; clang -DALLOW_ICMP_FRAG_NEEDED -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DSKIP_DEBUG]"; clang -DSKIP_DEBUG -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DHAVE_LPM_TRIE_MAP_TYPE]"; clang -DHAVE_LPM_TRIE_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DHAVE_LRU_HASH_MAP_TYPE]"; clang -DHAVE_LRU_HASH_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4]"; clang -DENABLE_IPV4 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DENABLE_IPSEC]"; clang -DENABLE_IPV4 -DENABLE_IPSEC -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DHAVE_LPM_TRIE_MAP_TYPE]"; clang -DENABLE_IPV4 -DHAVE_LPM_TRIE_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE]"; clang -DENABLE_IPV4 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DENABLE_IPV4_FRAGMENTS]"; clang -DENABLE_IPV4 -DENABLE_IPV4_FRAGMENTS -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6]"; clang -DENABLE_IPV6 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DENABLE_IPSEC]"; clang -DENABLE_IPV6 -DENABLE_IPSEC -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE]"; clang -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE]"; clang -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DENABLE_IPV4]"; clang -DENABLE_IPV6 -DENABLE_IPV4 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DENABLE_IPV4 -DENABLE_ROUTING]"; clang -DENABLE_IPV6 -DENABLE_IPV4 -DENABLE_ROUTING -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV6 -DENABLE_IPV4 -DENABLE_IPSEC -DENABLE_ENCAP_HOST_REMAP]"; clang -DENABLE_IPV6 -DENABLE_IPV4 -DENABLE_IPSEC -DENABLE_ENCAP_HOST_REMAP -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE]"; clang -DENABLE_IPV4 -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_IPV4 -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE -DENABLE_TPROXY]"; clang -DENABLE_IPV4 -DENABLE_IPV6 -DHAVE_LPM_TRIE_MAP_TYPE -DHAVE_LRU_HASH_MAP_TYPE -DENABLE_TPROXY -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_HOST_REDIRECT -DENABLE_IPV4 -DENABLE_IPV6]"; clang -DENABLE_HOST_REDIRECT -DENABLE_IPV4 -DENABLE_IPV6 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_HOST_REDIRECT -DENABLE_IPV4 -DENABLE_IPV6 -DENABLE_NAT46]"; clang -DENABLE_HOST_REDIRECT -DENABLE_IPV4 -DENABLE_IPV6 -DENABLE_NAT46 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_NODEPORT -DENABLE_IPV4 -DENABLE_IPV6]"; clang -DENABLE_NODEPORT -DENABLE_IPV4 -DENABLE_IPV6 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;   :  " [-DENABLE_NODEPORT -DENABLE_DSR -DENABLE_IPV4 -DENABLE_IPV6]"; clang -DENABLE_NODEPORT -DENABLE_DSR -DENABLE_IPV4 -DENABLE_IPV6 -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -o /dev/null bpf_lxc.ll;  \
fi
clang -DENABLE_IPV4 -DENABLE_IPV6 -DENABLE_HOST_REDIRECT -DENABLE_NAT46 -DENABLE_ROUTING -DENABLE_IPSEC -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include -I/home/ubuntu/go/src/github.com/cilium/cilium/bpf -D__NR_CPUS__=2 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll
In file included from bpf_lxc.c:5:
In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/include/bpf/api.h:15:
/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include/linux/../bpf/builtins.h:264:24: error: passing
      'const void *' to parameter of type 'void *' discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        return __builtin_bcmp(x, y, len);
                              ^
/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include/linux/../bpf/builtins.h:264:27: error: passing
      'const void *' to parameter of type 'void *' discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        return __builtin_bcmp(x, y, len);
                                 ^
In file included from bpf_lxc.c:5:
In file included from /home/ubuntu/go/src/github.com/cilium/cilium/bpf/include/bpf/api.h:16:
/home/ubuntu/go/src/github.com/cilium/cilium/bpf/include/linux/../bpf/tailcall.h:32:10: error: unknown register
      name 'r0' in asm
                     : "r0", "r1", "r2", "r3", "r4", "r5");
                       ^
3 errors generated.
Makefile:186: recipe for target 'bpf_lxc.ll' failed
make[1]: *** [bpf_lxc.ll] Error 1
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf'
Makefile:132: recipe for target 'bpf' failed
make: *** [bpf] Error 2

```

**Comment by aanm** [comment]
hello @k82cn, do you have all requirements  specified in [here](https://docs.cilium.io/en/latest/contributing/development/dev_setup/#requirements)?

**Comment by k82cn** [comment]
@aanm , thanks very for your info; the error was fixed after upgrading llvm & clang to 10.0+ :)
