### PR TITLE
v1.11 backports 2023-04-12

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #24715 -- pkg/bandwidth: add error for bandwidth manager not being enabled (@aanm)
 - [x] #24711 -- docs: Fix upgradeCompatibility references (@joestringer)
 - [x] #24723 -- tests: add exceptions for lease errors due to etcd (@jibi)
     - Trivial conflicts.
 - [x] #24681 -- pkg/service: Handle leaked backends (@aditighag)
     - Several compilation errors due to silent conflicts.
     - I had to add some missing logfields.
 - [x] #24769 -- loader: Don't compile `.asm` files by default (@pchaigno)
     - Trivial conflict.
 - [x] #24773 -- ipsec: Clean up stale XFRM policies and states (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 24715 24711 24723 24681 24769 24773; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.11

**Review by joestringer — APPROVED** [review]
For the backport of the commit I authored :+1:

File: pkg/service/service.go [hunk 1]
```diff
@@ -861,6 +869,35 @@ func (s *Service) restoreBackendsLocked() error {
...
+			// duplicate backends could have previously established active connections,
+			// and these connections can get disrupted. However, the leaks likely
+			// happened when service entries were deleted, so those connections
+			// were also expected to be terminated.
+			// Regardless, delete the duplicates as this can affect restoration of current
+			// active backends, and may prevent new backends getting added as map
+			// size is limited, which can result in connectivity issues.
+			id := b.ID
+			DeleteBackendID(id)
+			if err := s.lbmap.DeleteBackendByID(id); err != nil {
```
Comment (aditighag) [inline pkg/service/service.go]:
```suggestion
			if err := s.lbmap.DeleteBackendByID(id, b.L3n4Addr.IsIPv6()); err != nil {
```

File: pkg/service/service.go [hunk 2]
```diff
@@ -861,6 +869,35 @@ func (s *Service) restoreBackendsLocked() error {
...
+				log.Errorf("unable to delete duplicate backend: %v", id)
+			}
+			log.WithFields(logrus.Fields{
+				logfields.BackendID:        b.ID,
+				logfields.L3n4Addr:         b.L3n4Addr,
+				logfields.BackendState:     b.State,
```
Comment (aditighag) [inline pkg/service/service.go]:
```suggestion
	log.WithFields(logrus.Fields{
                                logfields.BackendID:        b.ID,
                                logfields.L3n4Addr:         b.L3n4Addr,
                        }).Info("Duplicate backend entry not restored")
```

File: pkg/service/service.go [hunk 3]
```diff
@@ -479,20 +479,28 @@ func (s *Service) GetDeepCopyServices() []*lb.SVC {
...
 	defer s.Unlock()
+	var errs error
+	backendsById := make(map[lb.BackendID]struct{})
 
-	// Restore backend IDs
-	if err := s.restoreBackendsLocked(); err != nil {
-		return err
+	// Restore service cache from BPF maps
+	if err := s.restoreServicesLocked(backendsById); err != nil {
+		errs = multierr.Append(errs,
```
Comment (aditighag) [inline pkg/service/service.go:497]: Please add the missing import - 

`"go.uber.org/multierr"`

(This would go after `"github.com/sirupsen/logrus"`.)
Also, please run `go mod tidy && go mod vendor` and commit the changes.

File: pkg/service/service.go [hunk 4]
```diff
@@ -479,20 +479,28 @@ func (s *Service) GetDeepCopyServices() []*lb.SVC {
...
+			fmt.Errorf("error while restoring services: %w", err))
 	}
 
-	// Restore service cache from BPF maps
-	if err := s.restoreServicesLocked(); err != nil {
-		return err
+	// Restore backend IDs
+	if err := s.restoreBackendsLocked(backendsById); err != nil {
+		errs = multierr.Append(errs,
```
Comment (aditighag) [inline pkg/service/service.go:503]: This should be resolved by the missing import above.

**Review by aditighag — CHANGES_REQUESTED** [review]
Suggested changes to resolve the linter errors. If it's tedious for you, I can push to your branch. Thanks!

**Review by jibi — APPROVED** [review]

File: pkg/service/service.go (hunk 1 above)
Comment (pchaigno) [reply pkg/service/service.go]: The one backport PR where I don't run `git rebase --exec "make build" origin/v1.11` :facepalm: Thanks for the pointers Aditi!

**Comment by pchaigno** [comment]
/test-backport-1.11

**Review by aanm — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Thanks a lot!

**Comment by pchaigno** [comment]
I've run additional checks against my two PRs to confirm they are still implementing the expected behavior. All looks good.

**Comment by gandro** [comment]
Two of the 4.9 Jenkins pipelines failed with the following error:
```
2023-04-12T11:28:40.977814650Z level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.0.1.254 fd04::12 tunnel vxlan 8472 <nil> cilium_host cilium_net 1500 false false false /run/cilium/cgroupv2 /sys/fs/bpf false true v3 3 false true]" error="exit status 1" subsys=datapath-loader
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/1284/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2559/testReport/junit/Suite-k8s-1/21/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

This is also an issue on the other v1.11 backport PR: https://github.com/cilium/cilium/pull/24852#issuecomment-1506148470

**Comment by gandro** [comment]
- net-next simply timed out https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2646/testReport/Suite-k8s-1/16/K8sDatapathConfig_Iptables_Skip_conntrack_for_pod_traffic/
- ConformanceAKS failed talking to the AKS apiserver, likely an infra flake. Restarting.  ` 🟥 Error reading Cilium logs: error getting cilium-agent logs for kube-system/cilium-gkgm7: Get "https://10.224.0.4:10250/containerLogs/kube-system/cilium-gkgm7/cilium-agent?sinceTime=2023-04-12T09%3A53%3A17Z&timestamps=true": write unix @->/tunnel-uds/proxysocket: write: broken pipe` https://github.com/cilium/cilium/actions/runs/4676748724/jobs/8283442868

**Comment by gandro** [comment]
/ci-aks-1.11

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
- ci-aks keeps failing with infrastructure issues. This time the konnectivity-agent is in a crashloopbackoff, blocking cilium-cli from obtaining cilium status. This is a infrastructure flake and unrelated to the PR
- kernel 4.9 is known broken on v1.11, see https://github.com/cilium/cilium/pull/24823#issuecomment-1506558088

This means that all three red test are unrelated failures. Merging this PR.
