### PR TITLE
datapath/loader: fix privileged test build

### PR DESCRIPTION
**Pull request by tklauser**
These got broken by commit 6882e98baf7c ("datapath: always generate BTF
debug information") in PR #14166:

 	 # github.com/cilium/cilium/pkg/datapath/loader [github.com/cilium/cilium/pkg/datapath/loader.test]
	 pkg/datapath/loader/loader_test.go:198:24: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 pkg/datapath/loader/loader_test.go:255:28: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 pkg/datapath/loader/loader_test.go:283:27: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 make: *** [tests-privileged] Error 1

Fixes: 6882e98baf7c ("datapath: always generate BTF debug information")

### CODE REVIEW

**Comment by tklauser** [comment]
test-runtime

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
retest-runtime

**Comment by tklauser** [comment]
Runtime tests passed (which run the privileged tests fixed in this PR), marking as ready to merge.

**Review by nebril — APPROVED** [review]
