### PR TITLE
v1.5 backports 2019-05-27

### PR DESCRIPTION
**Pull request by brb**
v1.5 backports 2019-05-27

BACKPORTED:

 * #8067 -- cni: Fix incorrect logging in failure case (@joestringer)
 * #8050 -- test: add v1.15.0-beta.0 to the CI (@aanm)
 * #8086 -- add support for k8s 1.14.2 (@aanm)
 * #8083 -- pkg/maps: use pointer in receivers for GetKeyPtr and GetValuePtr (@aanm) -- to avoid compilation errors I had to add https://github.com/cilium/cilium/pull/8124/commits/4d6475cc65cedd60e63579060e074699b5f1e901.
 * #8090 -- docs: update well-known-identities documentation (@aanm)
 * #8105 -- Recover from ginkgo fail in WithTimeout helper (@nebril)
 * #8097 -- proxylib: Fix egress enforcement (@jrajahalme)
 * #8118 -- test: fix incorrect deletion statement for policy (@ianvernon)
 * #7870 -- CI: Log at INFO and above for all unit tests (@iffyio)

NOT BACKPORTED:

 * #8080 -- maps/metricsmap: fix cilium bpf metrics list output (@aanm) -- this depends on #7708 which was reverted.

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8067 8050 8086 8083 8090 8105 8097 8118 7870; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8124)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Compilation error:

```
[2019-05-27T14:57:37.518Z]     k8s1-1.10: ../pkg/maps/sockmap/sockmap.go:113:4: cannot use k (type SockmapKey) as type bpf.MapKey in return argument:
[2019-05-27T14:57:37.518Z]     k8s1-1.10: 	SockmapKey does not implement bpf.MapKey (GetKeyPtr method has pointer receiver)
[2019-05-27T14:57:37.518Z]     k8s1-1.10: ../pkg/maps/sockmap/sockmap.go:113:4: cannot use v (type SockmapValue) as type bpf.MapValue in return argument:
[2019-05-27T14:57:37.518Z]     k8s1-1.10: 	SockmapValue does not implement bpf.MapValue (GetValuePtr method has pointer receiver)
```

**Comment by brb** [comment]
Fixed the error by pushing https://github.com/cilium/cilium/pull/8124/commits/4d6475cc65cedd60e63579060e074699b5f1e901 /cc @aanm

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Travis failed due to:

```
# github.com/cilium/cilium/proxylib [github.com/cilium/cilium/proxylib.test]
proxylib/proxylib_test.go:651:70: undefined: debug
```

The `debug` const was introduced in https://github.com/cilium/cilium/pull/7870. Adding the PR to the backport.

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2077/execution/node/104/log/ - etcd appears to not have been able to allocate identities.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
CI run had connectivity issues
```
	 kube-system   cilium-etcd-operator-c77fb5c9f-7d5v8   0/1       ImagePullBackOff    0          10m       192.168.36.12   k8s2      <none>
```

**Comment by tgraf** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Hit #7797
