### PR TITLE
bpf: Avoid implicit conversion loses integer precision

### PR DESCRIPTION
**Pull request by sayboras**
This is to avoid the below error, while trying to compile with clang 20.1.2

```
./lib/icmp6.h:98:45: error: implicit conversion loses integer precision: '__u64' (aka 'unsigned long long') to '__u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
   98 |         if (ctx_change_tail(ctx, ctx_full_len(ctx) + ICMP6_ND_OPT_LEN, 0) < 0)
      |             ~~~~~~~~~~~~~~~      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

File: bpf/lib/icmp6.h [hunk 1]
```diff
@@ -95,7 +95,7 @@ int icmp6_ndisc_adv_addopt(struct __ctx_buff *ctx)
 	void *data, *data_end;
 	__u64 *opt;
 
-	if (ctx_change_tail(ctx, ctx_full_len(ctx) + ICMP6_ND_OPT_LEN, 0) < 0)
+	if (ctx_change_tail(ctx, (__u32)(ctx_full_len(ctx) + ICMP6_ND_OPT_LEN), 0) < 0)
```
Comment (gentoo-root) [inline bpf/lib/icmp6.h:98]: Hmm, I wonder why it didn't happen with older clang versions. We have this warning enabled.

**Review by gentoo-root — APPROVED** [review]

File: bpf/lib/icmp6.h (hunk 1 above)
Comment (sayboras) [reply bpf/lib/icmp6.h:98]: could be the some bug fix in 20.1.2, I have been using clang 20 for a while, just got this error after upgrade.
